name: Mirror to Destination
on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:Dan13615/website.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
